### ISSUE TITLE
v2.5.2 does not build

### ISSUE THREAD

**Issue by IzzySoft** [adamff-dev/spam-call-blocker-app#39]
First, the APK claims to have been built from commit a57380c180173a6d59af70171a47fd33208e3242 – a commit that does not exist in this repo (either it was never pushed, or it was squashed). Second, even ignoring that and building from the tagged commit, the build fails:

```
> Task :app:compileReleaseKotlin FAILED
e: file:///build/repo/app/src/main/java/com/addev/listaspam/util/SpamUtils.kt:140:17 Unresolved reference: normalizedNumber
e: file:///build/repo/app/src/main/java/com/addev/listaspam/util/SpamUtils.kt:157:46 Type mismatch: inferred type is String? but String was expected
e: file:///build/repo/app/src/main/java/com/addev/listaspam/util/SpamUtils.kt:163:42 Type mismatch: inferred type is String? but String was expected
e: file:///build/repo/app/src/main/java/com/addev/listaspam/util/SpamUtils.kt:166:21 Type mismatch: inferred type is String? but String was expected
e: file:///build/repo/app/src/main/java/com/addev/listaspam/util/SpamUtils.kt:175:43 Type mismatch: inferred type is String? but String was expected
e: file:///build/repo/app/src/main/java/com/addev/listaspam/util/SpamUtils.kt:183:21 Type mismatch: inferred type is String? but String was expected
e: file:///build/repo/app/src/main/java/com/addev/listaspam/util/SpamUtils.kt:193:51 Type mismatch: inferred type is String? but String was expected
e: file:///build/repo/app/src/main/java/com/addev/listaspam/util/SpamUtils.kt:196:25 Type mismatch: inferred type is String? but String was expected
e: file:///build/repo/app/src/main/java/com/addev/listaspam/util/SpamUtils.kt:212:21 Type mismatch: inferred type is String? but String was expected
e: file:///build/repo/app/src/main/java/com/addev/listaspam/util/SpamUtils.kt:225:49 Type mismatch: inferred type is String? but String was expected
e: file:///build/repo/app/src/main/java/com/addev/listaspam/util/SpamUtils.kt:229:21 Type mismatch: inferred type is String? but String was expected
e: file:///build/repo/app/src/main/java/com/addev/listaspam/util/SpamUtils.kt:239:42 Type mismatch: inferred type is String? but String was expected
e: file:///build/repo/app/src/main/java/com/addev/listaspam/util/SpamUtils.kt:245:21 Type mismatch: inferred type is String? but String was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
```

So what was the APK built from now? If it was a commit you forgot to push, can you please urgently push it? Otherwise, this release would be marked with "failed to reproduce" – and people might wonder if there's some danger involved (like, something having been "secretly injected" into the APK – which is what [Reproducible Builds](https://izzyondroid.org/about/security/ReproducibleBuilds/) shall rule out, among other things).

Thanks in advance!

**Comment by adamff-dev** [comment]
Fixed. Thanks for letting me know.

**Comment by IzzySoft** [comment]
Fixed how? Ah, new release! Good, thanks! Let me try…

**Comment by IzzySoft** [comment]
OK, that one is RB – but won't go anywhere, as you forgot to increase `versionCode` 🙈

**Comment by Selu84k** [comment]
Conclusion? This apk is not secure, is it?

**Comment by IzzySoft** [comment]
@Selu84k not the correct conclusion.

* it is RB: it was confirmed the APK was indeed built from the indicated source
* forgot to increase `versionCode`: if you have the previous version installed, you won't get this offered as update – as Android thinks it's the very same (Android internally uses `versionCode` to check if an APK offers a newer version than the one installed)

**Comment by adamff-dev** [comment]
versionCode fixed. Try again, please.

**Comment by IzzySoft** [comment]
Confirmed both: `versionCode` fixed, and APK builds reproducibly – thanks!
